[package]
name = "day16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.2"
itertools = "0.10.5"
pathfinding = "4.1.1"
petgraph = "0.6.2"
priority-queue = "1.3.0"
