---
name: Benchmark

on: [push]

jobs:
  criterion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run criterion for baseline 
        continue-on-error: true
        working-directory: ./benchmark
        run: |
          git checkout HEAD^ 
          cargo bench --bench criterion -- --verbose --save-baseline previous
      - name: Run criterion on new commit
        working-directory: ./benchmark
        run: |
          git checkout -
          cargo bench --bench criterion -- --verbose --baseline previous || cargo bench --bench criterion -- --verbose
      - name: Upload criterion reports
        uses: actions/upload-artifact@v2
        with:
          name: target-criterion
          path: target/criterion

  iai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install valgrind
        run: sudo apt install -y valgrind
      - name: Run iai
        working-directory: ./benchmark
        run: cargo bench --bench iai
